"""add average_rating to scheme

Revision ID: 2267f6eea6d6
Revises: 351def1f7880
Create Date: 2025-04-12 20:33:19.612376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2267f6eea6d6'
down_revision = '351def1f7880'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('average_rating', sa.Float(), nullable=False, server_default='0.0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheme', schema=None) as batch_op:
        batch_op.drop_column('average_rating')

    # ### end Alembic commands ###
