"""Added document and process column to Scheme table

Revision ID: 99efa7f11eb2
Revises: 2267f6eea6d6
Create Date: 2025-04-18 12:56:50.151033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99efa7f11eb2'
down_revision = '2267f6eea6d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('process', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('documents', sa.Text(), nullable=True))
        batch_op.drop_column('benefit_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('benefit_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('documents')
        batch_op.drop_column('process')

    # ### end Alembic commands ###
